apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuvector-manager-pod
  namespace: neuvector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neuvector-manager-pod
  template:
    metadata:
      labels:
        app: neuvector-manager-pod
    spec:
      imagePullSecrets:
        - name: regsecret-gcp
      containers:
        - name: neuvector-manager-pod
          #image: 10.1.127.3:5000/neuvector/manager:jenkins-manager-1728
          image: registry.neuvector.com/manager:4.4.2

          imagePullPolicy: Always
          env:
            - name: CTRL_SERVER_IP
              value: neuvector-svc-controller.neuvector
          volumeMounts:
            - mountPath: /var/neuvector
              name: nv-share
              readOnly: false
      restartPolicy: Always
      volumes:
        - name: nv-share
          hostPath:
            path: /home/neuvector/var/neuvector

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuvector-controller-pod
  namespace: neuvector
spec:
  minReadySeconds: 100
  replicas: 3
  selector:
    matchLabels:
      app: neuvector-controller-pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: neuvector-controller-pod
    spec:
      imagePullSecrets:
        - name: regsecret-gcp
      containers:
        - name: neuvector-controller-pod
#         image: 10.1.127.3:5000/neuvector/controller:latest
          image: registry.neuvector.com/controller:4.4.2
          imagePullPolicy: Always
          securityContext:
            privileged: true
          lifecycle:
            preStop:
              exec:
                # SIGTERM triggers a quick exit; gracefully terminate instead
#                command: ["/usr/local/bin/teardown.sh"]
                command: ["/usr/local/bin/consul", "leave"]
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/ready
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: CLUSTER_JOIN_ADDR
              value: neuvector-svc-controller.neuvector
            - name: CLUSTER_ADVERTISED_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CLUSTER_BIND_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CTRL_PATH_DEBUG
              value: "1"
            - name: CTRL_PERSIST_CONFIG
              value: "1"
          volumeMounts:
            - mountPath: /var/neuvector
              name: nv-share
              readOnly: false
            - mountPath: /var/run/docker.sock
              name: docker-sock
              readOnly: false
            - mountPath: /host/proc
              name: proc-vol
              readOnly: true
            - mountPath: /host/cgroup
              name: cgroup-vol
              readOnly: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      volumes:
        - name: nv-share
          hostPath:
            path: /home/neuvector/var/neuvector
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: proc-vol
          hostPath:
            path: /proc
        - name: cgroup-vol
          hostPath:
            path: /sys/fs/cgroup

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: neuvector-scanner-pod
  namespace: neuvector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: neuvector-scanner-pod
  template:
    metadata:
      labels:
        app: neuvector-scanner-pod
    spec:
      imagePullSecrets:
        - name: regsecret-gcp
      containers:
        - name: neuvector-scanner-pod
          image: registry.neuvector.com/scanner:latest
          imagePullPolicy: Always
          env:
            - name: CLUSTER_JOIN_ADDR
              value: neuvector-svc-controller.neuvector
      restartPolicy: Always

