---
# Source: core/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: neuvector-svc-controller
  namespace: default
  labels:
    chart: core-1.8.8
    release: nv
    heritage: Helm
spec:
  clusterIP: None
  ports:
    - port: 18300
      protocol: "TCP"
      name: "cluster-tcp-18300"
    - port: 18301
      protocol: "TCP"
      name: "cluster-tcp-18301"
    - port: 18301
      protocol: "UDP"
      name: "cluster-udp-18301"
  selector:
    app: neuvector-controller-pod
