---
# Source: core/templates/crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nvsecurityrules.neuvector.com
  labels:
    chart: core-1.8.8
    release: nv
    heritage: Helm
spec:
  group: neuvector.com
  names:
    kind: NvSecurityRule
    listKind: NvSecurityRuleList
    plural: nvsecurityrules
    singular: nvsecurityrule
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
---
# Source: core/templates/crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nvclustersecurityrules.neuvector.com
  labels:
    chart: core-1.8.8
    release: nv
    heritage: Helm
spec:
  group: neuvector.com
  names:
    kind: NvClusterSecurityRule
    listKind: NvClusterSecurityRuleList
    plural: nvclustersecurityrules
    singular: nvclustersecurityrule
  scope: Cluster
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
---
# Source: core/templates/crd.yaml
# ClusterRole for NeuVector to operate CRD
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-customresourcedefinition
  labels:
    chart: core-1.8.8
    release: nv
    heritage: Helm
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - watch
  - create
  - get
---
# Source: core/templates/crd.yaml
# ClusterRole for NeuVector to manager user-created CRD rules
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-nvsecurityrules
  labels:
    chart: core-1.8.8
    release: nv
    heritage: Helm
rules:
- apiGroups:
  - neuvector.com
  resources:
  - nvsecurityrules
  - nvclustersecurityrules
  verbs:
  - list
  - delete
---
# Source: core/templates/crd.yaml
# ClusterRoleBinding for NeuVector to operate CRD
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-customresourcedefinition
  labels:
    chart: core-1.8.8
    release: nv
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: neuvector-binding-customresourcedefinition
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
---
# Source: core/templates/crd.yaml
# ClusterRoleBinding for NeuVector to manager user-created CRD rules
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-nvsecurityrules
  labels:
    chart: core-1.8.8
    release: nv
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: neuvector-binding-nvsecurityrules
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
---
# Source: core/templates/crd.yaml
apiVersion: v1
kind: Service
metadata:
  name: neuvector-svc-crd-webhook
  namespace: default
  labels:
    chart: core-1.8.8
    release: nv
    heritage: Helm
spec:
  ports:
    - port: 443
      targetPort: 30443
      protocol: TCP
      name: crd-webhook
  type: ClusterIP
  selector:
    app: neuvector-controller-pod
