---
# Source: core/templates/crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nvsecurityrules.neuvector.com
  labels:
    chart: core-1.8.8
    release: RELEASE-NAME
    heritage: Helm
spec:
  group: neuvector.com
  names:
    kind: NvSecurityRule
    listKind: NvSecurityRuleList
    plural: nvsecurityrules
    singular: nvsecurityrule
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              egress:
                items:
                  properties:
                    action:
                      type: string
                    applications:
                      items:
                        type: string
                      type: array
                    name:
                      type: string
                    ports:
                      type: string
                    priority:
                      type: integer
                    selector:
                      properties:
                        criteria:
                          items:
                            properties:
                              key:
                                type: string
                              op:
                                type: string
                              value:
                                type: string
                            type: object
                          type: array
                        name:
                          type: string
                        original_name:
                          type: string
                      type: object
                  type: object
                type: array
              file:
                items:
                  properties:
                    app:
                      items:
                        type: string
                      type: array
                    behavior:
                      type: string
                    filter:
                      type: string
                    recursive:
                      type: boolean
                  type: object
                type: array
              ingress:
                items:
                  properties:
                    action:
                      type: string
                    applications:
                      items:
                        type: string
                      type: array
                    name:
                      type: string
                    ports:
                      type: string
                    priority:
                      type: integer
                    selector:
                      properties:
                        criteria:
                          items:
                            properties:
                              key:
                                type: string
                              op:
                                type: string
                              value:
                                type: string
                            type: object
                          type: array
                        name:
                          type: string
                        original_name:
                          type: string
                      type: object
                  type: object
                type: array
              process:
                items:
                  properties:
                    action:
                      type: string
                    name:
                      type: string
                    path:
                      type: string
                  type: object
                type: array
              target:
                properties:
                  policymode:
                    type: string
                  selector:
                    properties:
                      criteria:
                        items:
                          properties:
                            key:
                              type: string
                            op:
                              type: string
                            value:
                              type: string
                          type: object
                        type: array
                      name:
                        type: string
                      original_name:
                        type: string
                    type: object
                type: object
            required:
            - target
            type: object
        type: object
---
# Source: core/templates/crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nvclustersecurityrules.neuvector.com
  labels:
    chart: core-1.8.8
    release: RELEASE-NAME
    heritage: Helm
spec:
  group: neuvector.com
  names:
    kind: NvClusterSecurityRule
    listKind: NvClusterSecurityRuleList
    plural: nvclustersecurityrules
    singular: nvclustersecurityrule
  scope: Cluster
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              egress:
                items:
                  properties:
                    action:
                      type: string
                    applications:
                      items:
                        type: string
                      type: array
                    name:
                      type: string
                    ports:
                      type: string
                    priority:
                      type: integer
                    selector:
                      properties:
                        criteria:
                          items:
                            properties:
                              key:
                                type: string
                              op:
                                type: string
                              value:
                                type: string
                            type: object
                          type: array
                        name:
                          type: string
                        original_name:
                          type: string
                      type: object
                  type: object
                type: array
              file:
                items:
                  properties:
                    app:
                      items:
                        type: string
                      type: array
                    behavior:
                      type: string
                    filter:
                      type: string
                    recursive:
                      type: boolean
                  type: object
                type: array
              ingress:
                items:
                  properties:
                    action:
                      type: string
                    applications:
                      items:
                        type: string
                      type: array
                    name:
                      type: string
                    ports:
                      type: string
                    priority:
                      type: integer
                    selector:
                      properties:
                        criteria:
                          items:
                            properties:
                              key:
                                type: string
                              op:
                                type: string
                              value:
                                type: string
                            type: object
                          type: array
                        name:
                          type: string
                        original_name:
                          type: string
                      type: object
                  type: object
                type: array
              process:
                items:
                  properties:
                    action:
                      type: string
                    name:
                      type: string
                    path:
                      type: string
                  type: object
                type: array
              target:
                properties:
                  policymode:
                    type: string
                  selector:
                    properties:
                      criteria:
                        items:
                          properties:
                            key:
                              type: string
                            op:
                              type: string
                            value:
                              type: string
                          type: object
                        type: array
                      name:
                        type: string
                      original_name:
                        type: string
                    type: object
                type: object
            required:
            - target
            type: object
        type: object
---
# Source: core/templates/crd.yaml
# ClusterRole for NeuVector to operate CRD
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-customresourcedefinition
  labels:
    chart: core-1.8.8
    release: RELEASE-NAME
    heritage: Helm
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - watch
  - create
  - get
---
# Source: core/templates/crd.yaml
# ClusterRole for NeuVector to manager user-created CRD rules
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: neuvector-binding-nvsecurityrules
  labels:
    chart: core-1.8.8
    release: RELEASE-NAME
    heritage: Helm
rules:
- apiGroups:
  - neuvector.com
  resources:
  - nvsecurityrules
  - nvclustersecurityrules
  verbs:
  - list
  - delete
---
# Source: core/templates/crd.yaml
# ClusterRoleBinding for NeuVector to operate CRD
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-customresourcedefinition
  labels:
    chart: core-1.8.8
    release: RELEASE-NAME
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: neuvector-binding-customresourcedefinition
subjects:
- kind: ServiceAccount
  name: default
  namespace: neuvector
---
# Source: core/templates/crd.yaml
# ClusterRoleBinding for NeuVector to manager user-created CRD rules
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: neuvector-binding-nvsecurityrules
  labels:
    chart: core-1.8.8
    release: RELEASE-NAME
    heritage: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: neuvector-binding-nvsecurityrules
subjects:
- kind: ServiceAccount
  name: default
  namespace: neuvector
---
# Source: core/templates/crd.yaml
apiVersion: v1
kind: Service
metadata:
  name: neuvector-svc-crd-webhook
  namespace: neuvector
  labels:
    chart: core-1.8.8
    release: RELEASE-NAME
    heritage: Helm
spec:
  ports:
    - port: 443
      targetPort: 30443
      protocol: TCP
      name: crd-webhook
  type: ClusterIP
  selector:
    app: neuvector-controller-pod
